# Generated by Django 3.1 on 2020-09-04 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminapp', '0001_initial'),
        ('Vendorapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('qty', models.IntegerField()),
                ('total', models.FloatField()),
                ('status', models.CharField(max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('address', models.TextField()),
                ('items', models.ManyToManyField(to='Vendorapp.FoodItemsModel')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerRegistrationModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('contactno', models.IntegerField(unique=True)),
                ('address', models.TextField(max_length=100)),
                ('password', models.CharField(max_length=20)),
                ('otp', models.IntegerField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.citymodel')),
            ],
        ),
    ]
