# Generated by Django 3.1 on 2020-09-04 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorRegistrationModel',
            fields=[
                ('v_id', models.AutoField(primary_key=True, serialize=False)),
                ('v_stall_name', models.CharField(max_length=200)),
                ('v_contact1', models.IntegerField(unique=True)),
                ('v_contact2', models.IntegerField(unique=True)),
                ('v_stall_photo', models.ImageField(upload_to='vendor_images/')),
                ('v_stall_address', models.TextField()),
                ('v_password', models.CharField(max_length=10)),
                ('v_otp', models.IntegerField()),
                ('v_cuisine_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.cuisinemodel')),
                ('v_stall_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.citymodel')),
            ],
        ),
        migrations.CreateModel(
            name='FoodTypeModel',
            fields=[
                ('food_id', models.AutoField(primary_key=True, serialize=False)),
                ('food_type', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=3000)),
                ('food_photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vendorapp.vendorregistrationmodel')),
                ('vendor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.cuisinemodel')),
            ],
        ),
        migrations.CreateModel(
            name='FoodItemsModel',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=500)),
                ('item_price', models.FloatField()),
                ('item_pic', models.ImageField(upload_to='food_images/')),
                ('item_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vendorapp.foodtypemodel')),
            ],
        ),
    ]
