# Generated by Django 3.1 on 2020-09-04 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CuisineModel',
            fields=[
                ('cuisine_id', models.AutoField(primary_key=True, serialize=False)),
                ('cuisine_name', models.CharField(max_length=200, unique=True)),
                ('cuisine_photo', models.ImageField(upload_to='cuisine_images/')),
            ],
        ),
        migrations.CreateModel(
            name='StateModel',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=200, unique=True)),
                ('state_photo', models.ImageField(upload_to='state_images/')),
            ],
        ),
        migrations.CreateModel(
            name='CityModel',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=200, unique=True)),
                ('city_photo', models.ImageField(upload_to='city_images/')),
                ('city_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.statemodel')),
            ],
        ),
    ]
